package com.pracas.presentation;

import javax.swing.GroupLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.BevelBorder;

/**
 *
 * @author arkey
 */
public class PartidaFrame extends javax.swing.JFrame {
	
	static final int MAX_CASELLES = 9;
	
	static final double relacio = 1.618034;
	int alturaFinestra = 560;
	int ampladaFinestra = (int) (alturaFinestra * relacio);
	
	static final int margeVertical = 29;
	static final int margeHoritzontal = 29;
	
	static final int longitudText = 92;
	static final double prcEspaiEntreCaselles = 0.5;
	
	int numCaselles;
	
    /**
     * Creates new form PartidaFrame
     */
    public PartidaFrame() {
		this.setMinimumSize(new Dimension(ampladaFinestra, alturaFinestra));
		this.setTitle("Partida");
		numCaselles = 0;
		initComponents();
    }
    
    public void setNumCaselles(int numCaselles) {
    	for (int i = 0; i < caselles.length; ++i) {
    		if (i < numCaselles) caselles[i].setVisible(true);
    		else caselles[i].setVisible(false);
    	}
    	this.numCaselles = numCaselles;
    	configPanellCaselles();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
    	
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        
        labelPunts = new JLabel();
        labelErrors = new JLabel();
        
        textPunts = new JTextField();
        textErrors = new JTextField();
        
        panellPrincipal = new JPanel();
        panellInfo = new JPanel();
        panellCaselles = new JPanel();
        panellBotons = new JPanel();
        
        caselles = new JTextField[MAX_CASELLES];
        for (int i = 0; i < caselles.length; ++i) {
        	caselles[i] = new JTextField();
        	caselles[i].setMinimumSize(new Dimension(56, 56));
        	caselles[i].setText("   ");
        }

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPunts.setText("Puntuacio: ");
        labelErrors.setText("Errors: ");
        
        textPunts.setText("0");
        textErrors.setText("0");
        
        textPunts.setEditable(false);
        textErrors.setEditable(false);
        
        
        jButton2.setText("Cancel");

        jButton1.setText("Login");
        jButton1.setMaximumSize(new java.awt.Dimension(60, 29));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        this.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
            	
                alturaFinestra = e.getComponent().getSize().height;
                ampladaFinestra = e.getComponent().getSize().width;
                configPanellCaselles();
            }
        });
        
        configPanellPrincipal();
        configPanellInfo();
        configPanellCaselles();
        configPanellBotons();
        this.setContentPane(panellPrincipal);

        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
	private void configPanellPrincipal() {
				
    	GroupLayout PanellPrincipalLayout = new GroupLayout(panellPrincipal);
    	panellPrincipal.setLayout(PanellPrincipalLayout);
        
        PanellPrincipalLayout.setHorizontalGroup(
        PanellPrincipalLayout.createSequentialGroup()
        	.addGap(margeHoritzontal)
        	.addGroup(PanellPrincipalLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
        		.addComponent(panellInfo)
	        	.addComponent(panellCaselles)
	        	.addComponent(panellBotons))
	        .addGap(margeHoritzontal)
        );
        
        PanellPrincipalLayout.setVerticalGroup(
        PanellPrincipalLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addGroup(PanellPrincipalLayout.createSequentialGroup()
	        	.addGap(margeVertical)
	        	.addComponent(panellInfo)
	        	.addGap(29)
	        	.addComponent(panellCaselles)
	        	.addGap(29)
	        	.addComponent(panellBotons)
	        	.addGap(margeVertical))
        );
    }

	
	
    private void configPanellInfo() {
    	
        GroupLayout PanellInfoLayout = new GroupLayout(panellInfo);
        panellInfo.setLayout(PanellInfoLayout);
        
        panellInfo.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));        
        
        PanellInfoLayout.setHorizontalGroup(
        PanellInfoLayout.createSequentialGroup()
	        .addGap(29)
	        .addGroup(PanellInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addComponent(labelPunts)
	        	.addComponent(labelErrors))
	        .addGap(11)
	        .addGroup(PanellInfoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addComponent(textPunts, longitudText, longitudText, longitudText)
	        	.addComponent(textErrors, longitudText, longitudText, longitudText))
	        .addGap(29)
        );    
            
            
        PanellInfoLayout.setVerticalGroup(
        PanellInfoLayout.createSequentialGroup()
        .addGap(29)
        .addGroup(PanellInfoLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
        	.addGroup(PanellInfoLayout.createSequentialGroup()
        		.addComponent(labelPunts)
        		.addGap(21)
        		.addComponent(labelErrors))
        	.addGroup(PanellInfoLayout.createSequentialGroup()
            	.addComponent(textPunts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
            	.addGap(16)
                .addComponent(textErrors, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
	    .addGap(29)
        );    
    }

    
    
    
    private void configPanellCaselles() {
    	
    	double numerador = ampladaFinestra - 2*margeHoritzontal;
    	double denominador = numCaselles + (numCaselles + 1)*prcEspaiEntreCaselles;
        int longCasella = (int) (numerador/denominador);
        		
        int espai = (int) (longCasella * prcEspaiEntreCaselles);
    	
        panellCaselles.setMinimumSize(new Dimension(ampladaFinestra - 2*margeHoritzontal - 1, 1));
        
        GroupLayout PanellCasellesLayout = new GroupLayout(panellCaselles);
        panellCaselles.setLayout(PanellCasellesLayout);
        
        PanellCasellesLayout.setHorizontalGroup(
        PanellCasellesLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
        .addGroup(PanellCasellesLayout.createSequentialGroup()
        	.addGap(espai)
        	.addComponent(caselles[0], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[1], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[2], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[3], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[4], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[5], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[6], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[7], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	.addComponent(caselles[8], longCasella, longCasella, longCasella)
        	.addGap(espai)
        	)
        );
        
        PanellCasellesLayout.setVerticalGroup(
        PanellCasellesLayout.createSequentialGroup()
        	.addGap(29)
        	.addGroup(PanellCasellesLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
        		.addComponent(caselles[0], longCasella, longCasella, longCasella)
        		.addComponent(caselles[1], longCasella, longCasella, longCasella)
        		.addComponent(caselles[2], longCasella, longCasella, longCasella)
        		.addComponent(caselles[3], longCasella, longCasella, longCasella)
        		.addComponent(caselles[4], longCasella, longCasella, longCasella)
        		.addComponent(caselles[5], longCasella, longCasella, longCasella)
        		.addComponent(caselles[6], longCasella, longCasella, longCasella)
        		.addComponent(caselles[7], longCasella, longCasella, longCasella)
        		.addComponent(caselles[8], longCasella, longCasella, longCasella))
        	.addGap(29)       
        ); 
        
            
    }
    
    private void configPanellBotons() {
    	
        GroupLayout PanellBotonsLayout = new GroupLayout(panellBotons);
        panellBotons.setLayout(PanellBotonsLayout);
        
        PanellBotonsLayout.setHorizontalGroup(
        PanellBotonsLayout.createSequentialGroup()
        
        );    
    }
	
    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    
    private JLabel labelPunts;
    private JLabel labelErrors;
    
    private JTextField textPunts;
    private JTextField textErrors;
    
    private JPanel panellPrincipal;
    private JPanel panellInfo;
    private JPanel panellCaselles;
    private JPanel panellBotons;
    
    private JTextField[] caselles;
    // End of variables declaration
}
